image: node
stages:
  - test
  - build
  - deploy
testJS:
  stage: test
  script:
    - yarn
    - npm run test
    - npm run e2e
buildJS:
  stage: build
  artifacts:
    paths:
      - _site/  # This is what we want to publish, replace with your `dist` directory

  script:
    - npm run build

deployApp:
  image: "python:latest"
  stage: deploy
  dependencies:
    - buildJS
  before_script:
    - pip install awscli # Install the SDK
  script:
    - aws s3 cp _site s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive # Replace example-bucket with your bucket

