before_script:
  - apt-get -qq update && apt-get -qq install npm
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - npm install @angular/cli yarn -g
build:
  stage: build
  script:
    - yarn install
    - ng build
    - docker build -t test .

