before_script:
  - apt-get -qq update
  - apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - apt-get install docker-ce
build:
  stage: build
  script:
    - docker build -t test .

