before_script:
  - apt-get -qq update
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - apt-get install docker-ce
build:
  stage: build
  script:
    - docker build -t test .

